import { loadDOM } from './load-page'

export const PARSE_DATE_REGEX = /(\d){1,2}\s([а-я]+)?(\s)?((\d){4})?/gi
export const REFILL_INTERVAL = 1000 * 60 * 60 * 3

const mainRoot = 'body > div.g-page > div.l-content.m-content > div > div.col70.m-cola > div > div > div.col50.m-cola'

export const SELECTORS = {
    events: `${mainRoot} > article.b-postcard`,
    cities: `${mainRoot} > div.page-head > h1 > select:nth-child(2) > option`,
    topics: `${mainRoot} > div.page-head > h1 > select:nth-child(3) > option`,
    singleEventPicture:
        'body > div.g-page > div.l-content.m-content > div.l-content-wrap > div.cell.g-right-shadowed.mobtab-maincol > div.event-info > img',
}

export const defaultTags = {
    topics: [
        '.NET',
        '1C',
        '3D',
        'Agile',
        'AI',
        'Algorithms',
        'Android',
        'APL',
        'BA',
        'big data',
        'Blockchain',
        'C',
        'C++',
        'Clojure',
        'cloud',
        'Data Science',
        'Database',
        'DevOps',
        'Erlang',
        'F#',
        'Flash',
        'Front-end',
        'gamedev',
        'Go',
        'golang',
        'Groovy',
        'hardware',
        'Haskell',
        'highload',
        'HR',
        'iOS',
        'IoT',
        'Java',
        'JavaScript',
        'Kotlin',
        'Linux',
        'Lisp',
        'Lua',
        'Microsoft',
        'ML',
        'mobile',
        'Perl',
        'PHP',
        'PM',
        'Python',
        'QA',
        'R',
        'Ruby',
        'Rust',
        'SaaS',
        'Sales',
        'Scala',
        'Scrum',
        'VR',
        'английский',
        'безопасность',
        'бизнес',
        'благотворительность',
        'вебинар',
        'вечеринка',
        'вечерника',
        'дайджест',
        'дизайн',
        'карьера',
        'клубные встречи',
        'конкурс',
        'конференция',
        'курсы',
        'маркетинг',
        'менеджмент',
        'семинар',
        'сертификация',
        'соревнование',
        'соревнования',
        'стартап',
        'тестирование',
        'технологии',
        'ФП',
        'фриланс',
        'хакатон',
    ],
    places: [
        'Алушта',
        'Амстердам',
        'Анахейм',
        'Атланта',
        'Афины',
        'Белая Церковь',
        'Берлин',
        'Бостон',
        'Братислава',
        'Брно',
        'Брюссель',
        'Будапешт',
        'Бухарест',
        'Варшава',
        'Вена',
        'Вильнюс',
        'Винница',
        'Вроцлав',
        'Гданьск',
        'Гродно',
        'Днепр',
        'Донецк',
        'Дорнбирн',
        'Екатеринбург',
        'Житомир',
        'Запорожье',
        'Ивано-Франковск',
        'Ирпень',
        'Казань',
        'Киев',
        'Копенгаген',
        'Краков',
        'Краматорск',
        'Кременчуг',
        'Кривой Рог',
        'Кропивницкий',
        'Курортное',
        'Лондон',
        'Луганск',
        'Луцк',
        'Львов',
        'Мариуполь',
        'Мелитополь',
        'Минск',
        'Москва',
        'Мюнхен',
        'Николаев',
        'Новосибирск',
        'Нью-Йорк',
        'Одесса',
        'Оксфорд',
        'Орхус',
        'Осло',
        'Остин',
        'Париж',
        'Познань',
        'Полтава',
        'Прага',
        'Рига',
        'Ровно',
        'Самара',
        'Сан-Франциско',
        'Санкт-Петербург',
        'Санта-Клара',
        'Севастополь',
        'Северодонецк',
        'Симферополь',
        'Сиэтл',
        'Сиэттл',
        'Солигорск',
        'София',
        'Сплит',
        'Спокан',
        'Стамбул',
        'Стокгольм',
        'Сумы',
        'Таллинн',
        'Тель-Авив',
        'Тернополь',
        'Турку',
        'Ужгород',
        'Флоренция',
        'Харьков',
        'Хельсинки',
        'Херсон',
        'Хмельницкий',
        'Челябинск',
        'Черкассы',
        'Чернигов',
        'Черновцы',
        'Чешке-Будейовице',
        'Шацк',
        'online',
    ],
}

export function getTags() {
    return loadDOM().then(dom => {
        if (dom) {
            const places: string[] = []
            const topics: string[] = []

            dom.window.document.querySelectorAll(SELECTORS.cities).forEach(elem => {
                let place = elem.textContent
                if (place === 'онлайн') place = 'online'
                places.push(place)
            })

            dom.window.document.querySelectorAll(SELECTORS.topics).forEach(elem => {
                topics.push(elem.textContent)
            })

            return { topics, places }
        }
    })
}
